FROM node:18-alpine AS deps
# RUN apk add --no-cache libc6-compat
WORKDIR /app1

COPY package.json yarn.lock ./
COPY . ./
RUN yarn install --frozen-lockfile
# RUN set -ex; \
#     yarn install --frozen-lockfile --production; \
#     yarn cache clean; 
# RUN yarn build

FROM node:18-alpine AS builder
WORKDIR /app1
# COPY --from=deps /app1/node_modules ./node_modules
COPY . ./

ENV NEXT_TELEMETRY_DISABLED 1

# RUN yarn build
# RUN set -ex; \
#     yarn install --frozen-lockfile --production; \
#     yarn cache clean; \
#     yarn run build

FROM node:18-alpine AS runner
WORKDIR /app1
# COPY ./package.json /package.json 
COPY package.json yarn.lock ./
COPY . .
# ENV NODE_ENV production
ENV NEXT_TELEMETRY_DISABLED 1

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

# COPY --from=builder --chown=nextjs:nodejs /app1/.next ./.next
# COPY --from=builder /app1/node_modules ./node_modules
# COPY --from=builder /app1/package.json ./package.json

USER nextjs

EXPOSE 8080

ENV PORT 8080

CMD ["yarn", "dev"]
